on:
  push:

jobs:
  cd:
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        conf:
          - name: keruta-admin
            manifestFile: ./keruta/keruta-admin.yaml
            repository: kigawa-net/kigawa-net-k8s
            harborProject: "library"
            branch: develop
            targetEnv: dev
          - name: keruta-admin
            manifestFile: ./keruta/keruta-admin.yaml
            repository: kigawa-net/kigawa-net-k8s
            harborProject: "library"
            branch: beta
            targetEnv: beta
    uses: ./.github/workflows/release.yml
    with:
      conf:
        name: keruta-admin
        manifestFile: ./keruta/keruta-admin.yaml
        repository: kigawa-net/kigawa-net-k8s
        harborProject: "library"
        branch: develop
        targetEnv: dev
